package com.mycompany.telalogin;

/**
 *
 * @author Tawaf
 */
public class Principal_tela extends javax.swing.JFrame {

    /**
     * Creates new form Principal_tela
     */
    public Principal_tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrar_livro = new javax.swing.JMenu();
        cadastrar_usuário = new javax.swing.JMenu();
        locacoes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrar_livro.setText("Cadastrar livro");
        cadastrar_livro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar_livroMouseClicked(evt);
            }
        });
        jMenuBar1.add(cadastrar_livro);

        cadastrar_usuário.setText("Cadastrar usuário");
        cadastrar_usuário.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrar_usuárioMouseClicked(evt);
            }
        });
        jMenuBar1.add(cadastrar_usuário);

        locacoes.setText("Locações");
        jMenuBar1.add(locacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar_usuárioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar_usuárioMouseClicked
        // TODO add your handling code here:
        Cadastro cadastroUsuario = new Cadastro();
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_cadastrar_usuárioMouseClicked

    private void cadastrar_livroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrar_livroMouseClicked
        Cadastro_livro cadastro_livro = new Cadastro_livro();
        cadastro_livro.setVisible(true);
    }//GEN-LAST:event_cadastrar_livroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Principal_tela principal = new Principal_tela();
        principal.setLocationRelativeTo(null);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadastrar_livro;
    private javax.swing.JMenu cadastrar_usuário;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu locacoes;
    // End of variables declaration//GEN-END:variables
}
